### ISSUE TITLE
Can't build after v1.14.2 update

### ISSUE THREAD

**Issue by KiminRyu** [BranchMetrics/android-branch-deep-linking#262]
Error:Failed to resolve: com.crashlytics.sdk.android:answers:1.3.6
<a href="openFile:/home/kimin/workspace/Android/educast-android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

I can build my project just 3 hours ago, but I can not build my project with above error message.
I integrated branch with your document, and I didn't do other feature things with branch io

**Comment by aaustin** [comment]
Hey @KiminRyu - We're working on a fix for this right now, and should have a patch in the next 12 hours. In the meantime, can you add `jcenter` to your gradle.build file? It should look like so:
```
repositories {
  jcenter()
}
```

**Comment by KiminRyu** [comment]
I solved it by using specific version in gradle file(document recommend
using 1+). so this problem is due to my gradle cache or something. I'm
sorry for bothering you!

2016년 6월 22일 수요일, Alex Austin<notifications@github.com>님이 작성한 메시지:

> Hey @KiminRyu <https://github.com/KiminRyu> - We're working on a fix for
> this right now, and should have a patch in the next 12 hours. In the
> meantime, can you add jcenter to your gradle.build file? It should look
> like so:
>
> repositories {
>   jcenter()
> }
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/BranchMetrics/android-branch-deep-linking/issues/262#issuecomment-227638215>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHZmlyZGuWzz6BmisAgSqHS85vFosJcxks5qOLXQgaJpZM4I7Y3j>
> .
>


-- 
서울대학교 전기정보공학부 11'
류 기 민
Seoul National University
Electrical & Computer Engineering
Kimin Ryu

**Comment by rabross** [comment]
Target 1.14.0 till the issue is resolved.

**Comment by sojanpr** [comment]
@KiminRyu @rabross  Sorry that you faced this issue. We have added a much cleaner  fix and released v1.14.3 . Could you please update and try

**Comment by KiminRyu** [comment]
this is my gradle file in app module.

```gradle
repositories {
    jcenter()
   maven { url "https://jitpack.io" }
}

dependencies {
   ...
    compile 'io.branch.sdk.android:library:1.+'
   ...
}
```

and console still shows this error message(I rebuild and clean my project)
```
Error:Failed to resolve: com.crashlytics.sdk.android:answers:1.3.6
<a href="openFile:/home/kimin/workspace/Android/educast-android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```

but I tried to specify the version like 1.14.3 or any other version, it works fine.

**Comment by sojanpr** [comment]
1.14.3 is the latest version. So `compile 'io.branch.sdk.android:library:1.+'` should be fine . It may be a temporary update issue from maven. Could you please try a gradle sync

**Comment by sojanpr** [comment]
@KiminRyu  did the  grade sync helped to get the latest SDK version ?
