### ISSUE TITLE
Launching deeplink from within the app returns empty referral parameters

### ISSUE THREAD

**Issue by carloshwa** [BranchMetrics/android-branch-deep-linking#617]
1. Create a valid deep-link URL
2. Launch the URL from within the app:
```
Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(deepLinkUrl));
startActivity(intent);
```
3. When `BranchReferralInitListener.onInitFinished(JSONObject referringParams, BranchError error)` gets called when calling `Branch.getInstance().initSession()`, `referringParams` is empty.

I have modified the Branchster sample app to demonstrate this in the following branch:
https://github.com/carloshwa/Branch-Example-Deep-Linking-Branchster-Android/tree/launch_deep_link_from_app

Here is my change to the sample app to launch a deep-link from the app (tap your monster to launch a deep-link to my monster):
https://github.com/carloshwa/Branch-Example-Deep-Linking-Branchster-Android/commit/e06738f2598239b417fad0f2aa041e1aceb37c86
You can see `branchUniversalObject` in `SplashActivity` is null when the app is launched.

**Comment by heliomartins** [comment]
I'm inclined to say that I'm facing the same issue.

After a deep analyse I manage to verify that: Once the session has been started, clicking in a link inside the app, the jsonObject with the meta values returns an object with no values inside. 
However, if I pause() or destroy() the app, the `https://api2.branch.io/v1/close` is called and when I return to the app everything works fine, "simply" because the API ` https://api2.branch.io/v1/open` was called again.

My apologies if I missed something in the documentation.

**Clicking at the Deeplink immediately after opening the app. (works fine).**
![image](https://user-images.githubusercontent.com/2566718/49785596-365f0d00-fd75-11e8-9c0b-a74e4ce2c7db.png)

**Clicking at Deepling straight after the previous action. Didn't pause nor close the app. (Empty values)**
![image](https://user-images.githubusercontent.com/2566718/49785754-a66d9300-fd75-11e8-8e3d-9c9e729ee94e.png)

Thanks for the assistance BranchMetrics team.

**Comment by code-crusher** [comment]
Hey @carloshwa and @heliomartins, 

Thanks for the explanation. Your debugging is correct. To support the intra-app deep linking, we have to pass extra intent data as per the docs here: https://docs.branch.io/pages/apps/android/#handle-links-in-your-own-app

**Code snippet to trigger Branch link:**
```java
Intent intent = new Intent(this, ActivityToLaunch.class);
intent.putExtra("branch","http://xxxx.app.link/testlink");
intent.putExtra("branch_force_new_session",true);
startActivity(intent);
```

The _branch_force_new_session_ informs the Branch SDK to make a new session in the case the session is already existing. 

Can you test this and let me know if your issue is resolved?

**Comment by heliomartins** [comment]
I've made lot's of tests, and it didn't work. I'm still getting the same behaviour.
I had actually tried your approach before.

![image](https://user-images.githubusercontent.com/2566718/49842350-46c3c600-fe0f-11e8-99e0-c2e5f86f32f7.png)

**Comment by carloshwa** [comment]
@code-crusher Thanks for following up. I did find that documentation later on, however I have not yet implemented it. The use case I am dealing with is if I have a `TextView` within the app with hyperlinks in the text that are made tappable using `Linkify`. Some of these hyperlinks may be a deep-link URL for my app. I would like it so if the user opens that link, it will launch the deep-link into the app. So in order to properly handle that, I have to intercept the user opening that link and fire a custom Intent with `branch_force_new_session` set, which is non-trivial (I think I would need to create my own implementation of `Linkify` that handles my app's deep-link URLs separately).

@heliomartins I think in your example, you would need to set `branch_force_new_session` in the intent you used to start `BranchActivity`, not in the intent you are using to start `WelcomeActivity`.

**Comment by heliomartins** [comment]
@carloshwa, thanks for your reply.

Yes, the above was one of my tries. Unfortunately, I might not be able to have the outcome I want.

What I'm trying to do is an integration with Intercom and Branch.io. The _Deeplink_ is inside one of the Intercom campaigns. Intercom provides some Activities and Fragments which does not allow me to add intents.

In summary, this is the flow:
**Blue** are my classes.
**Red** 3rd Party Framework
![image](https://user-images.githubusercontent.com/2566718/49861251-8d391500-fe4f-11e8-80da-cb086dd75a22.png)

If anyone has any tips or have faced similar problems, I would love to get some input.

Thanks heaps!

**Comment by andregpsoft** [comment]
I have the same problem. When the app is running in background or foreground the referringParams will be empty. Works ok for cold starts. 😟

**Comment by csalmi-branch** [comment]
@heliomartins @carloshwa and @andregpsoft, are you still facing the same issue?

**Comment by carloshwa** [comment]
Hi @csalmi-branch,
I think at this point, this issue is more of a feature request than bug report. It would be nice to support intra-app deep linking without having to set `branch_force_new_session` explicitly, in order to support the use case I described here:
https://github.com/BranchMetrics/android-branch-deep-linking/issues/617#issuecomment-446468274

Thanks!

**Comment by csalmi-branch** [comment]
@carloshwa Thanks for the response! I'll backlog a ticket for the team to investigate this further.

**Comment by ibracero** [comment]
I'm facing exactly the same issue, `referringParams` is empty when the app is in foreground

**Comment by Psrinath-branch** [comment]
Hi @ibracero - Can you provide more details about the issue you're facing? If its the same as the above, can you please submit an FR to support@branch.io? 

Thanks!

**Comment by ibracero** [comment]
It's exactly the same case, clicking the deeplink (push notification):

- With the app in background / closed:
![image](https://user-images.githubusercontent.com/19324743/50759280-7de59580-125c-11e9-80b3-775ab9bd9da1.png)

- With the app in foreground:
![image](https://user-images.githubusercontent.com/19324743/50759333-ab324380-125c-11e9-8060-fcf406713753.png)

**Comment by aaustin** [comment]
So, there are a lot of people chiming in here regarding the supposed issue of "params not being retrieved in warm start". Reading through, there seems to be a lot of confusion about the actual context for the original request, and I think a few of you folks are getting the issue confused.

The original request is to handle the scenario of loading a deep link WITHIN the app. So, in essence, programmatically clicking a Branch link from one activity to load another. This won't work out of the box because we won't reset the active user session unless all activities are backgrounded. So, Vatsal's suggestion of ```intent.putExtra("branch_force_new_session",true);``` will force us to reset the session and retrieve new parameters.

However, if you're encountering an issue where you are clicking a link from a completely different app, and the parameters are not loading from a warm start, this is unexpected behavior and an integration issue. In this scenario, technically what is happening is that the new deep link intent that includes the Branch link is not properly received by our SDK. Here are common integration mistakes that can cause that:
1. You are not overriding `onNewIntent` in your routing activity:
```
@Override
public void onNewIntent(Intent intent) {
  this.setIntent(intent);
}
```
2. You did not set your activity to `singleTask`

```android:launchMode="singleTask"```

3. You are not passing the `this.getIntent().getData()` to initSession call in `onStart`.

If you are in the camp of the second problem, and you check that you are doing the above 3 things correctly, then please submit a ticket to integrations@ where we can work more closely with you.

**Comment by ibracero** [comment]
Hey @aaustin, in our app, we have a SplashActivity (here we handle the deeplinks) which leads to a HomeScreen and finishes itself.

With that premise, we cannot set our SplashActivity `launchMode` to `singleTask` because every time we launch the app (even if it's already in background) it will launch from the scratch losing the state.

Anyways, we tried to follow your directions and still doesn't work. When `onNewIntent` is called we `initSession` but `referringParams` is still empty.

`intent.putExtra("branch_force_new_session",true);` doesn't work for us either, as we're not opening the link from within the app, but from a push notification.

So, just to clarify our issue:

1. We have the app in background
2. We receive a push notification with a deeplink
3. We tap the notification body
4. The `SplashActivity` is launched but `referringParams` is empty when we `initSession`

If the app is not in memory or It's in background, `referringParams` contains the expected parameters so we can process the deeplink successfully

**Comment by aaustin** [comment]
Hey Ibracero - Can you post a link to you SplashActivity.java and manifest code that I could review? Perhaps share a gist? I guarantee it's one of the above things that's causing this. If you're not comfortable sharing in the public thread so others can learn, please send a note to alex@branch.io with this info and I'll work with you 1 on 1, the post the solve here.

**Comment by heliomartins** [comment]
> @heliomartins @carloshwa and @andregpsoft, are you still facing the same issue?

Sorry for the late reply,
I had to make a workaround achieve what I was looking for.

Thanks anyway.

**Comment by code-crusher** [comment]
For the issue related to the _intra-app deep linking_ where the Branch links are clicked within the app itself in the foreground, we have created a sample with the usage linked here: https://drive.google.com/file/d/1rc9cMVE1O7ItLCNvyMTmgECm55D5mT92/view?usp=sharing

**Comment by csalmi-branch** [comment]
@aaustin and @ibracero were you able to sort out this issue through email?

**Comment by aaustin** [comment]
We've got a live debugging session scheduled for early next week. I'll post once we find the resolution.

**Comment by VvoidVano** [comment]
any news ？ @aaustin

**Comment by aaustin** [comment]
Hi @VvoidVano. Sorry that I forgot to post the update. We've determined that the SDK currently doesn't receive the new link data *in the following case only*:
1. App is in foreground
2. Notification received with Branch link
3. Notification tapped

The problem is that the SDK doesn't check the Intent in this case, because the Activity state doesn't call onResume when it's in foreground and a notification is clicked. Because it's isolated to a rare edge case, we haven't prioritized a fix but we're looking into it this week actually. cc @apeterson-branch

**Comment by code-crusher** [comment]
Hi all, quick update here, we have the solution internally in place, we will be releasing the fix in an SDK update soon. Will update here once we do.

**Comment by sojanpr** [comment]
Launching a new intent when application in 'foreground'  will work with the current Branch SDK. Below works for me.
1. Add following to the intent
 `branch_force_new_session = true`  
`branch =  my_deep_link_url`
(same with push intent)
2. initSession() should be called  inactivity "onResume()"
The key is moving `initSession()` to `onResume()`. Reason being application lifecycle listener has no method to intercept 'onNewIntent()'. So BranchSDK has no clue about the new intent until onResume() is happened an returns the previous deep link params if initSession is called before `onResume()`.

In the above case it make sense to initiaise in onResume() since onStart() will not be called in the above flow if activity is launch mode is `SingleTask` or  `SingleTop`.

**Comment by csalmi-branch** [comment]
We released v3.1.1 of the SDK which has a fix for this issue.

**Comment by ibracero** [comment]
I've tested it with v3.1.1 and this is still happening to me. I'll refresh my issue:
- **Scenario 1: App in background** If you tap a link / push notification while the app is in background, `referringParams` brings the right data so you can handle the deeplink fine.
- **Scenario 2: App in foreground** If you tap a push notification while your app is already there (foreground), `referringParams` will be empty.

I've checked all the solutions proposed above again with v3.1.1 and it still doesn't work.
- I cannot force my Activity's `launchMode` to `singleTask` because this causes a state loss situation: If you go background at any screen and then you open your app again, it will launch from the scratch.
- @sojanpr 's solution doesn't work either
- I've reviewed and followed the steps from [the docs ](https://github.com/BranchMetrics/android-branch-deep-linking#register-deep-link-router) and everything is working exactly the same as it did before v3.1.1

**Comment by code-crusher** [comment]
Hey @ibracero - we tested the same setup and it works - confirmed by other devs too. Would be open for a quick call next week and I work with you get this setup? Let me know. 

In the meanwhile, I'll create a sample app and share it with you.

**Comment by ibracero** [comment]
Sure! That sample app would be useful, thanks!

**Comment by BugsBunnyBR** [comment]
I got this working on 3.2.0 version and  this implementation:

``` kotlin
 val intent = activity.intent
        // WORKAROUND: When the user clicks in a BranchIO deeplink from within the app the default implementation fails to handle the
        // deeplink opening because a session is already active/open.
        // So we force the session to be open again with the parameters bellow. We need both of them!
        // This has a side effect, the callback will be called twice, the first time without the data, the second time with the deeplink data.
        intent.putExtra(Defines.Jsonkey.AndroidPushNotificationKey.key, activity.intent.data)
        intent.putExtra(Defines.Jsonkey.ForceNewBranchSession.key, true)
        activity.intent = intent
        return Maybe.create { emitter ->
            var count = 0
            branch.initSession({ referringParams, error ->
                if (!emitter.isDisposed) {
                    ++count
                    if (error != null) {
                        emitter.onError(BranchException(error))
                    } else {
                        val str = referringParams.optString(MY_APP_DEEPLINK_KEY, null)
                        if (!str.isNullOrBlank()) {
                            emitter.onSuccess(str)
                        } else if (count == 2) {
                            emitter.onComplete()
                        }
                    }
                }
            }, activity.intent.data, activity)
```

I still did not test this implementation thoroughly.

**Comment by ibracero** [comment]
This worked for me! thank you!

**Comment by Junaid-Sakib** [comment]
This only gives you the link, not the entire set of params.

**Comment by Junaid-Sakib** [comment]
This only gives you the link not the entire set of params - I wonder how this issue seems to be closed as I still face the problem even using the 4.0.0 version of the SDK.

**Comment by byamba3** [comment]
I'm still facing this issue on v4.2.0 unfortunately. Tried everything on this thread.

**Comment by dmotpan** [comment]
@byamba3 I was facing the same issue after updating from ~2.0 to 4.4.0:
- one problem was that since then the way of how Branch SDK determines has changed and I had to specify in manifest explicitly whether it's in test mode or not:
`<meta-data android:name="io.branch.sdk.TestMode" android:value="@bool/branch_test_mode" />`
- the other problem was that the SDK was initialized twice and at the moment it should have handled a deeplink, it was throwing an error that the SDK was already inizialized (inside `onInitFinished` callback). I solved it by initialized the SDK only once, inside launcher activity `onStart`
